# Generated by Django 4.2.20 on 2025-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterReads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='description',
            field=models.CharField(default='Hi!', max_length=70),
        ),
    ]
