# Generated by Django 4.2.20 on 2025-05-06 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterReads', '0002_alter_bookuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
