# Generated by Django 4.2.20 on 2025-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterReads', '0003_bookuser_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=600),
        ),
    ]
