# Generated by Django 4.2.20 on 2025-05-30 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betterReads', '0005_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MyShelf', max_length=400)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookshelf',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_shelf_user'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='betterReads.book'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
