# Generated by Django 4.2.20 on 2025-06-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterReads', '0006_activity'),
        ('betterReads', '0006_reviews_bookshelf_unique_shelf_user_reviews_book_and_more'),
    ]

    operations = [
    ]
