# Generated by Django 4.2.22 on 2025-06-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterReads', '0007_merge_20250607_0928'),
        ('betterReads', '0007_merge_20250607_1520'),
    ]

    operations = [
    ]
