# Generated by Django 4.2.22 on 2025-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterReads', '0008_merge_20250608_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
